### ISSUE TITLE
Xoodyak160

### ISSUE THREAD

**Issue by nixberg** [jedisct1/wasi-crypto-preview#16]
https://github.com/jedisct1/wasi-crypto-preview/blob/b75886d282a3d06abd677b9455b1996f025587a0/implementations/wasmtime/src/symmetric/xoodyak.rs#L83

Wouldn’t it be either `Xoodyak192` bits or `Ok(20)` bytes?

**Comment by jedisct1** [comment]
Good catch, thank you!
